server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # [추가] 실제 업로드된 파일이 위치한 경로 설정
    location /uploads/ {
        alias /usr/share/nginx/html/uploads/;
        autoindex off;
        access_log off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}